name: Java CI with Gradle

on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "*" ]  
  pull_request:  
    branches: [ "*" ] 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        env:
          MAVEN_OPTS: "-Xmx2048m --illegal-access=permit"

      - name: LS
        run: tree ./

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/*.jar
